### PR TITLE
Added New Toolbar, Sidebar, fixed css

### PR DESCRIPTION
**Pull request by dbhagesh**
New Toolbar
 - Toolbar is now a part of notebook and its stays fixed on the top
 - Got new look
 - New Feature Auto Save on any change to the notebook state
 
New Sidebar
- Simplified Icon Sidebar to match with the toolbar look

Fixed CSS
- Brought Back the last CSS fix as it was necessary while resizing the window
- Fixed Overflow Scroll Issue which is also mentioned in one of the issues
- Now user can provide the height and width it require from the Notebook

### CODE REVIEW

**Comment by echarles** [comment]
@dbhagesh Thank you so much for this contribution.

1. I had to commit a few changes regarding the height of the notebook (as the kernelname of the Jupyter Context), and your changes now collide with my latest commits. So sorry for that, but the good point is that we felt the same need and kind-of solved it the same way. Could you have a look at my latest commits and rebase your PR. Thx again!!!
2. I see in the changes for the CSS some very specific ids like `iv#id-0e1e4cbc-c431-4ce8-b16f-2d7563d93f4a` I feel there is other ways to address the scope of the CSS selector. I can see ways to simplify the CSS rules with more generic CSS selectors (so less specific) https://www.w3schools.com/cssref/css_selectors.asp.

**Comment by echarles** [comment]
> Brought Back the last CSS fix as it was necessary while resizing the window

@dbhagesh  I have indeed rolled-back some of the committed changes and introduced a width property. Latest master resize well here on width change, but I agree it does not resize on the height.

**Comment by dbhagesh** [comment]
Please have a look I have resolved the conflicts.
Yes, the CSS can be improved. But I had already mentioned that this is a temporary solution because I solved that issue as a third party developer. 
I will surely solve the CSS as first party developer by making changes inside the application itself as you suggest.
Till then you can merge this temporary solution.
Thankyou for the details, they help to improve and grow.

**Comment by echarles** [comment]
Thx @dbhagesh for the conflict resolution. For the CSS, anything that has a specific if (like e.g. 1b953030-ae64-4371-83f0-ea4b5d272842) should not be taken into account. What is the issue that those CSS rules are targeting. Maybe we could process in 2 steps: this PR without the CSS, and then I would try to solve the remaining issues related to CSS if you list what should be fixed.

**Comment by dbhagesh** [comment]
Sure,
No problem I will either I will separate the PR or fix these issues using CSS selectors and create a new PR.

Issues targeting are : 
- Taking Space according to the container in which the notebook is opened.
- Readjusting the height and width even if we are resizing the window manually.

**Comment by dbhagesh** [comment]
Can you  please look into the sidebar multiple entity issue and closing connection one ?

**Comment by echarles** [comment]
> No problem I will either separate the PR or fix these issues using CSS selectors and create a new PR.

Sounds good

> Issues targeting are :
> Taking Space according to the container in which the notebook is opened.
> Readjusting the height and width even if we are resizing the window manually.

Thx. We can tackle that, I think the width resizing is OK in latest main branch. I will check solutions for the rest

> Can you please look into the sidebar multiple entity issue and closing connection one ?

Sure, I will prioritise https://github.com/datalayer/jupyter-react/issues/27 and  https://github.com/datalayer/jupyter-react/issues/35

**Comment by echarles** [comment]
> Sure, I will prioritise https://github.com/datalayer/jupyter-react/issues/27 and https://github.com/datalayer/jupyter-react/issues/35

The good news is that I have release 0.0.20 which fixes those 2 issues. Please have a look at https://github.com/datalayer/jupyter-react/tree/884d61c6066e84862ff70bf0b4a6961efeb3e7fb/packages/react/src/examples for examples. Can you close the related issues if it works for you?

The bad news is that this PR has conflicts. I hope it won't take you too much time to resolve them.

**Comment by dbhagesh** [comment]
Thanks @echarles for those fixes.
I have fixed the css :
- Overflow Scroll
- Removed Extra white space appearing after allowing the scroll
- Height is fixed according to container and it resizes as well

For toolbar and sidebar I have upgraded them according to the new change introduced in the latest version.

**Review by echarles — APPROVED** [review]
This is really great contribution @dbhagesh. I have tested and the notebook resizes nicel. Merging. Thank you again so much.

Screenshot 2022-10-08 at 06 46 53

**Pull request merged**
